### ISSUE TITLE
Ashell F_ requesting a talk opportunity 

### ISSUE THREAD

**Issue by EntOfMD** [t1cgAcademy/t1cg-academy-talks#1]
**Your name:** Ashell Fernando

**Your talk topic:** Functions and Callbacks (and maybe Returns)

**Slack username:** https://columbiawebdevmeetup.slack.com/messages/DL4HTLH0R (Ash)

If you're not a member of our Slack, [click here to join](https://join.slack.com/t/columbiawebdevmeetup/shared_invite/enQtMzkzMTUwMDQ3ODE0LTBmYTM5Zjc2N2UwYzQ0OTUyMGUyMmJjOTk2OTk2NTc0OGE1Y2NhNDVkYWQ3M2NhMzEyNjBjNmVkNmQ5MGVlMzk)

**Length: (10-15 min):** 15 Minutes?

**Availability:**
_What month would you like to give your talk?:_ August meeting

**Comment by tony-decarlo-t1cg** [comment]
Approved for August 14 meetup!
