### ISSUE TITLE
Alexander Vela requesting a talk opportunity

### ISSUE THREAD

**Issue by alexandervela** [t1cgAcademy/t1cg-academy-talks#2]
**Your name:** Alexander Vela

**Your talk topic:** Bootstrap

**Slack username:** Alexander Vela

**Length: (10-15 min):** 10 - 15 mins sounds like a reasonable timeframe

**Availability:**
August 14th

**Comment by tony-decarlo-t1cg** [comment]
Approved for August 14 meetup!
